version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - ./node_modules/.bin/sls deploy --app spa
      - ./node_modules/.bin/sls syncToS3 --app spa
      - ./node_modules/.bin/sls invalidateCache --app spa
artifacts:
  files:
    - '**/*'
  base-directory: build